# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [6]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import pylab as pl
import numpy as np
%matplotlib inline

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [9]:
# Your code here :
from sklearn.model_selection import train_test_split

xmodel = data.drop("MEDV", axis = 1)
target = data["MEDV"]

x = xmodel
y = target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 30)

print(x_train.shape)
print(y_train.shape)

(404, 13)
(404,)


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [16]:
# Your code here :
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x_train, y_train)

y_pred_train = model.predict(x_train)
y_pred = model.predict(x_test)



## 3. Calculate and print R-squared for both the training and the testing set.

In [23]:
# Your code here
from sklearn.metrics import r2_score

print("The R2 score is:", r2_score(y_test, y_pred))

The R2 score is: 0.7181173900062079


## 4. Calculate and print mean squared error for both the training and the testing set.

In [24]:
# Your code here
from sklearn.metrics import mean_squared_error


print("The mean squared error for the testing set is :", mean_squared_error(y_test, y_pred))

The mean squared error for the testing set is : 17.933042188699176


In [32]:
import numpy as np

mse_test = mean_squared_error(y_test, y_pred)
rmse_test = np.sqrt(mse_test)
print("Root mean squared error (RMSE) for testing set:", rmse_test)

Root mean squared error (RMSE) for testing set: 4.234742281260948


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [33]:
# Your code here :
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("The mean absolute error is :", mae)

The mean absolute error is : 3.2254104069763145


## Classification Model Evaluation

In [34]:
from sklearn.datasets import load_iris
data = load_iris()

In [35]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [36]:
column_names = data.feature_names

In [37]:
df = pd.DataFrame(data['data'],columns=column_names)

In [42]:
df
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [ ]:
target = pd.DataFrame(data.target)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


In [40]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [41]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [47]:
# Your code here :
x = df
y = target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 69)


## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [48]:
# Your code here :
from sklearn.linear_model import LogisticRegression

modelLog = LogisticRegression()

modelLog.fit(x_train, y_train)

y_pred_training_set = modelLog.predict(x_train)
y_pred_testing_set = modelLog.predict(x_test)




## 8. Calculate and print the accuracy score for both the training and the testing set.

In [49]:
# Your code here :
from sklearn.metrics import accuracy_score

acc_training_set = accuracy_score(y_train, y_pred_training_set)
acc_testing_set = accuracy_score(y_test, y_pred_testing_set)

print("training set accuracy score: ", acc_training_set)
print("testing set accuracy score: ", acc_testing_set)

training set accuracy score:  0.9583333333333334
testing set accuracy score:  0.9666666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [50]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score

balanced_training_set = balanced_accuracy_score(y_train, y_pred_training_set)
balanced_testing_set = balanced_accuracy_score(y_test, y_pred_testing_set)

print("Balanced accuracy score for training set:", balanced_training_set)
print("Balanced accuracy score for testing set: ", balanced_testing_set)

Balanced accuracy score for training set: 0.9586466165413534
Balanced accuracy score for testing set:  0.9722222222222222


## 10. Calculate and print the precision score for both the training and the testing set.

In [51]:
# Your code here :
from sklearn.metrics import precision_score
precision_training_set = precision_score(y_train, y_pred_training_set, average='macro')
precision_testing_set = precision_score(y_test, y_pred_testing_set, average='macro')

print("Precision score for training set:", precision_training_set)
print("Precision score for testing set:", precision_testing_set)

Precision score for training set: 0.9580988117573485
Precision score for testing set: 0.9629629629629629


## 11. Calculate and print the recall score for both the training and the testing set.

In [52]:
# Your code here :
from sklearn.metrics import recall_score   
recall_training_set = recall_score(y_train, y_pred_training_set, average='macro')
recall_testing_set = recall_score(y_test, y_pred_testing_set, average='macro')

print("Recall score for training set:", recall_training_set)
print("Recall score for testing set:", recall_testing_set)

Recall score for training set: 0.9586466165413534
Recall score for testing set: 0.9722222222222222


## 12. Calculate and print the F1 score for both the training and the testing set.

In [53]:
# Your code here :
from sklearn.metrics import f1_score
f1_training_set = f1_score(y_train, y_pred_training_set, average='weighted')
f1_testing_set = f1_score(y_test, y_pred_testing_set, average='weighted')

print("F1 score for training set:", f1_training_set)
print("F1 score for testing set:", f1_testing_set)  

F1 score for training set: 0.9583528920878318
F1 score for testing set: 0.96692242114237


## 13. Generate confusion matrices for both the training and the testing set.

In [54]:
# Your code here :
from sklearn.metrics import confusion_matrix

confusion_training_set = confusion_matrix(y_train, y_pred_training_set)
confusion_testing_set = confusion_matrix(y_test, y_pred_testing_set)

print("Confusion matrix for training set:\n", confusion_training_set)
print("Confusion matrix for testing set:\n", confusion_testing_set) 

Confusion matrix for training set:
 [[40  0  0]
 [ 0 39  3]
 [ 0  2 36]]
Confusion matrix for testing set:
 [[10  0  0]
 [ 0  8  0]
 [ 0  1 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !